# Generated by Django 5.2.4 on 2025-08-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('bkash', 'Bkash'), ('nogod', 'Nagad'), ('sslcommerz', 'SSLCommerz')], default='manual', max_length=20),
        ),
    ]
