# Generated by Django 5.2.5 on 2025-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_reference_alter_transaction_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('bkash', 'Bkash'), ('nogod', 'Nagad'), ('rocket', 'Rocket')], max_length=20)),
                ('account_number', models.CharField(max_length=50)),
            ],
        ),
    ]
