# Generated by Django 5.2.4 on 2025-08-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(default='eurosespabd@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+8801911552077', max_length=20)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('messenger', models.URLField(blank=True, null=True)),
                ('phone_link', models.CharField(blank=True, max_length=20, null=True)),
                ('copyright', models.CharField(default='© 2025 Mike Sound Vai. All Rights Reserved.', max_length=255)),
            ],
        ),
    ]
