# Generated by Django 5.2.5 on 2025-08-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyDashboard',
        ),
        migrations.DeleteModel(
            name='ProductOrderReport',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='StaffOrderReport',
        ),
    ]
