# Generated by Django 5.2.4 on 2025-08-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('orders', '0006_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='city',
        ),
        migrations.RemoveField(
            model_name='courierassignment',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='courierassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='zones',
        ),
        migrations.CreateModel(
            name='OrderCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='confirmed', max_length=20)),
                ('auto_assigned', models.BooleanField(default=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courier.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_assignment', to='orders.order')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CourierAssignment',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
