# Generated by Django 5.2.4 on 2025-09-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_remove_zone_city_remove_courierassignment_courier_and_more'),
        ('orders', '0009_alter_order_status_alter_shipmenttracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercourier',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_assignments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ordercourier',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('delivered', 'Delivered')], default='assigned', max_length=20),
        ),
    ]
