# Generated by Django 5.2.6 on 2025-10-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_color_orderitem_image_orderitem_line_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='user_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
