# Generated by Django 5.2.5 on 2025-08-27 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_adsbanner_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.color'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'size', 'color')},
        ),
    ]
