# Generated by Django 5.2.4 on 2025-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_code_color_hex_code_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsbanner',
            name='image',
            field=models.ImageField(upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
    ]
