# Generated by Django 5.2.6 on 2025-10-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsbanner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
