# Generated by Django 5.2.6 on 2025-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_adsbanner_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsbanner',
            name='position',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
        migrations.AddField(
            model_name='product',
            name='offer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
