# Generated by Django 5.2.6 on 2025-10-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_subcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsbanner',
            old_name='type',
            new_name='offer_type',
        ),
        migrations.RemoveField(
            model_name='adsbanner',
            name='link',
        ),
    ]
